name: Ethan Hullett
description: "Ethan Hulletts personal website"
baseurl:
url: https://ethull.github.io
download: 
social:
  github: ethull
  email: ethan.hullett@btinternet.com
  facebook:
  twitter:
  instagram:
  tumblr:
author:
  name: Ethan Hullett
  bio: "Student at Kent University"
  email: ethan.hullett@btinternet.com
  image: /assets/images/author.jpg
  github: ethull
  facebook:
  twitter:
  instagram:
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
  - dev.sh
  - doc/
