name: Ethan Hullett
description: "Ethan Hulletts personal website"
baseurl:
url: https://ethull.github.io
download: 

social:
  github: ethull
  email: ethull@protonmail.com
  facebook:
  twitter:
  instagram:
  tumblr:

author:
  name: Ethan Hullett
  bio: "Student at Kent University"
  email: ethull@protonmail.com
  image: /assets/images/bella_boo.png
  github: ethull
  facebook:
  twitter:
  instagram:
  tumblr:
  show_on_post: true

permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
  - dev.sh
  - doc/
